import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import dotenv from 'dotenv';

const ENV_LOCAL_PATH = path.resolve(process.cwd(), '.env.local');
const ENV_DEV_LOCAL_PATH = path.resolve(process.cwd(), '.env.development.local');

const AI_KEY_PREFIXES = [
  'POLLY_',
  'GOOGLE_',
  'BEDROCK_',
  'STABILITY_',
  'ANTHROPIC_',
  'OPENAI_',
];

async function sync() {
  console.log('🔄 Syncing local environment...');

  let aiKeys: Record<string, string> = {};
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    const envLocalContent = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    const parsed = dotenv.parse(envLocalContent);
    
    for (const [key, value] of Object.entries(parsed)) {
      if (AI_KEY_PREFIXES.some(prefix => key.startsWith(prefix))) {
        aiKeys[key] = value;
      }
    }
    console.log(`✅ Extracted ${Object.keys(aiKeys).length} AI credentials from .env.local`);
  }

  let supabaseKeys: Record<string, string> = {};
  try {
    const statusOutput = execSync('npx supabase status -o json', { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] });
    const status = JSON.parse(statusOutput);
    
    supabaseKeys['NEXT_PUBLIC_SUPABASE_URL'] = 'http://127.0.0.1:54321';
    supabaseKeys['NEXT_PUBLIC_SUPABASE_ANON_KEY'] = status.anon_key;
    supabaseKeys['SUPABASE_SERVICE_ROLE_KEY'] = status.service_role_key;
    
    console.log('✅ Extracted local Supabase keys.');
  } catch (error) {
    console.error('❌ Failed to get Supabase status. Is Supabase running?');
    console.info('💡 Run "supabase start" to start the local Supabase instance.');
    process.exit(1);
  }

  const merged = {
    ...aiKeys,
    ...supabaseKeys,
  };

  const sortedKeys = Object.keys(merged).sort();
  
  const content = [
    '# GENERATED BY scripts/sync-local-env.ts',
    '# DO NOT EDIT MANUALLY - AI keys are synced from .env.local',
    '# Supabase keys are synced from local supabase status',
    '',
    ...sortedKeys.map(key => `${key}=${merged[key]}`)
  ].join('\n');

  fs.writeFileSync(ENV_DEV_LOCAL_PATH, content + '\n');
  console.log(`✨ Successfully generated ${ENV_DEV_LOCAL_PATH}`);
}

sync().catch((err) => {
  console.error('💥 Fatal error during sync:', err);
  process.exit(1);
});
