import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import dotenv from 'dotenv';

const ENV_LOCAL_PATH = path.resolve(process.cwd(), '.env.local');
const ENV_DEV_LOCAL_PATH = path.resolve(process.cwd(), '.env.development.local');

async function sync() {
  console.log('🔄 Syncing local environment...');

  let externalKeys: Record<string, string> = {};
  if (fs.existsSync(ENV_LOCAL_PATH)) {
    const envLocalContent = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    const parsed = dotenv.parse(envLocalContent);
    
    for (const [key, value] of Object.entries(parsed)) {
      const isSupabaseKey = key.includes('SUPABASE') && !key.startsWith('SUPABASE_AUTH_EXTERNAL_');
      const isPostgresKey = key.startsWith('POSTGRES_');

      if (!isSupabaseKey && !isPostgresKey) {
        externalKeys[key] = value;
      }
    }
    console.log(`✅ Extracted ${Object.keys(externalKeys).length} credentials from .env.local`);
  }

  let supabaseKeys: Record<string, string> = {};
  try {
    const statusOutput = execSync('npx supabase status -o json', { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] });
    
    // Strip non-JSON lines (like "Stopped services: ...")
    const jsonStart = statusOutput.indexOf('{');
    if (jsonStart === -1) throw new Error('No JSON object found in supabase status output');
    const jsonString = statusOutput.substring(jsonStart);
    
    const status = JSON.parse(jsonString);
    
    supabaseKeys['NEXT_PUBLIC_SUPABASE_URL'] = status.API_URL || 'http://127.0.0.1:54321';
    supabaseKeys['NEXT_PUBLIC_SUPABASE_ANON_KEY'] = status.ANON_KEY || status.anon_key;
    supabaseKeys['SUPABASE_SERVICE_ROLE_KEY'] = status.SERVICE_ROLE_KEY || status.service_role_key;
    
    console.log('✅ Extracted local Supabase keys.');
  } catch (error) {
    console.warn('⚠️  Could not get Supabase status. Using default local values.');
    supabaseKeys['NEXT_PUBLIC_SUPABASE_URL'] = 'http://127.0.0.1:54321';
    supabaseKeys['NEXT_PUBLIC_SUPABASE_ANON_KEY'] = 'local-anon-key-placeholder';
    supabaseKeys['SUPABASE_SERVICE_ROLE_KEY'] = 'local-service-role-key-placeholder';
  }

  const merged = {
    ...externalKeys,
    ...supabaseKeys,
  };

  const sortedKeys = Object.keys(merged).sort();
  
  const content = [
    '# GENERATED BY scripts/sync-local-env.ts',
    '# DO NOT EDIT MANUALLY - AI keys are synced from .env.local',
    '# Supabase keys are synced from local supabase status',
    '',
    ...sortedKeys.map(key => {
      const value = merged[key];
      if (value && (value.includes('{') || value.includes('\n') || value.includes(' '))) {
        return `${key}='${value}'`;
      }
      return `${key}=${value}`;
    })
  ].join('\n');

  fs.writeFileSync(ENV_DEV_LOCAL_PATH, content + '\n');
  console.log(`✨ Successfully generated ${ENV_DEV_LOCAL_PATH}`);
}

sync().catch((err) => {
  console.error('💥 Fatal error during sync:', err);
  process.exit(1);
});
