import { GoogleGenAI } from '@google/genai';
import { IImageGenerationProvider, ImageGenerationOptions, ImageGenerationResult } from '../types';

export class GoogleGenAIImageProvider implements IImageGenerationProvider {
    private project: string;
    private location: string;
    private credentials?: any;

    constructor() {
        this.project = process.env.GOOGLE_PROJECT_ID || '';
        this.location = 'global';

        if (process.env.GOOGLE_CREDENTIALS_JSON) {
            try {
                this.credentials = JSON.parse(process.env.GOOGLE_CREDENTIALS_JSON);
            } catch (e) {
                console.error("Failed to parse GOOGLE_CREDENTIALS_JSON", e);
            }
        }
    }

    async generateImage(options: ImageGenerationOptions): Promise<ImageGenerationResult> {
        if (!this.project) {
            throw new Error("GOOGLE_PROJECT_ID missing");
        }

        const ai = new GoogleGenAI({
            vertexai: true,
            project: this.project,
            location: this.location,
            googleAuthOptions: this.credentials ? { credentials: this.credentials } : undefined
        });

        const contents: any[] = [];

        if (options.subjectImage) {
            contents.push({
                inlineData: {
                    data: options.subjectImage.toString('base64'),
                    mimeType: 'image/png'
                }
            });
        }

        let finalPromptText = "";
        if (options.subjectImage) {
            finalPromptText = `
                Generate a professional-grade storybook illustration featuring the child whose photos are provided before and referenced as [1] in the prompt. 
                
                The scene depicts: ${options.prompt}. 
                
                The child [1] should remain the central character, carefully preserving their unique facial features, age, hair style, skin color, clothing, and identity from the reference photos. 
                
                Composition and Style: An eye-level medium shot with a soft, tactile children's book texture. Use a vibrant, harmonious color palette and warm, whimsical lighting to create a magical and inviting atmosphere. 
            `;
        } else {
            finalPromptText = `
                An enchanting children's book illustration depicting: ${options.prompt}. 
                The protagonist, ${options.characterDescription || 'the main character'}, is the focus of the scene. 
                
                Style: Vibrant colors, professional storybook art style with rich textures and a sense of wonder. 
            `;
        }

        contents.push({ text: finalPromptText });

        const modelId = 'gemini-2.5-flash-image';
        const config = {
            responseModalities: ["IMAGE"],
            imageConfig: {
                imageSize: options.imageSize || '1K'
            }
        };

        const response = await ai.models.generateContent({
            model: modelId,
            contents: contents,
            config
        });

        const candidates = response.candidates;
        const imagePart = candidates?.[0]?.content?.parts?.find(p => p.inlineData);

        if (!imagePart?.inlineData?.data) {
            console.error("Google GenAI Image Generation Failed. Candidates:", JSON.stringify(candidates, null, 2));
            throw new Error("No image generated by Google GenAI");
        }

        return {
            imageBuffer: Buffer.from(imagePart.inlineData.data, 'base64'),
            mimeType: imagePart.inlineData.mimeType || 'image/png',
            requestContext: {
                model: modelId,
                prompt: finalPromptText,
                config,
                hasSubjectImage: !!options.subjectImage,
            },
            responseMetadata: {
                finishReason: candidates?.[0]?.finishReason,
                citationMetadata: candidates?.[0]?.citationMetadata,
                safetyRatings: candidates?.[0]?.safetyRatings,
            },
            metadata: {
                prompt: finalPromptText,
                model: modelId,
                finishReason: candidates?.[0]?.finishReason
            }
        };
    }
}
